version: '3'
services:
  demo1:
    image: test-redis
    container_name: redis1
    network_mode: host
    ports:
      - 8190:8090
#  demo2:
#    image: test-redis
#    container_name: redis2
#    network_mode: host
#    ports:
#      - 8191:8090
networks:
  default:
    driver: bridge
#  redis:
#    image: redis
#    container_name: redis
#    ports:
#      - "6379:6379"
#    links:
#      - demo1
#      - demo2